#version 450

layout(set = 0, binding = 0) uniform UniformBufferObject {
    int element_count;
} ubo;

layout(set = 0, binding = 1, std430) readonly buffer InputBuffer {
    float input_buffer[];
};

layout(set = 0, binding = 2, std430) writeonly buffer OutputBuffer {
    float output_buffer[];
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index >= uint(ubo.element_count)) {
        return;
    }

    output_buffer[index] = max(input_buffer[index], 0.0);
}
