# automatically generated by the FlatBuffers compiler, do not modify

import flatbuffers


def ModelStart(builder):
    builder.StartObject(2)


def ModelAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)


def ModelAddWeights(builder, weights):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(weights), 0)


def ModelStartWeightsVector(builder, num_elements):
    return builder.StartVector(4, num_elements, 4)


def ModelEnd(builder):
    return builder.EndObject()
