# automatically generated by the FlatBuffers compiler, do not modify

import flatbuffers


def ModelStart(builder):
    builder.StartObject(2)


def ModelAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)


def ModelAddWeights(builder, weights):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(weights), 0)


def ModelStartWeightsVector(builder, num_elements):
    # StartVector(element_size, num_elements, alignment).
    # `weights` stores Tensor table offsets, which are 4-byte uoffset_t values;
    # the vector elements therefore have size 4 and require 4-byte alignment.
    return builder.StartVector(4, num_elements, 4)


def ModelEnd(builder):
    return builder.EndObject()
